# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Release 

on:
  workflow_dispatch:
    
jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run production-compile --if-present
    - run: npm run test
    - name: zip archive
      uses: vimtor/action-zip@v1.2
      with:
        files: web-editor/
        recursive: false
        dest: result.zip
    - name: Push web-site
      uses: Dylan700/sftp-upload-action@latest
      with:
        server: ${{ secrets.ftp_server }}
        username: ${{ secrets.ftp_user }}
        password: ${{ secrets.ftp_password }}
        uploads: ./web-editor/ => ./
        dry-run : true
    - name: Push archive
      uses: Dylan700/sftp-upload-action@latest
      with:
        server: ${{ secrets.ftp_server }}
        username: ${{ secrets.ftp_user }}
        password: ${{ secrets.ftp_password }}
        uploads: ./ => ./versions/
        ignore: |
          !.zip
        dry-run : true
        
